[common]
"site_name" = "Ritz のブログ"
"default_icatch_path" = "/image/rustacean-orig-noshadow.png"
"favicon_path" = "/icon/fox_girl_black_line_white.png"

[categories]
"Category slug file" = "Category Slug file"
"開発" = "development"
"日記" = "diary"

[tags]
"tag slug file" = "Tag Slug file"
"Rust" = "rust"
"Hello World" = "hello-world"
"Test" = "test"
