[common]
"site_name" = "Ritz のブログ"

[categories]
"Category slug file" = "Category Slug file"
"開発" = "development"
"日記" = "diary"

[tags]
"tag slug file" = "Tag Slug file"
"Rust" = "rust"
"Hello World" = "hello-world"
"Test" = "test"
