name: Cargo Test

on:
  pull_request:
    branches:
      - "master"
    paths:
      - "content/**"
      - "core/**"
      - "migration/**"
      - "templates/**"
      - ".env"
      - "Cargo.toml"
      - "Rocket.toml"
      - ".cargo/config.toml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run tests
        run: cargo test --workspace
